// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOP_5d1WOHCm3Q0gG-kT0oPHsH7ktMi_A',
    appId: '1:312635116271:web:817c4c66f7e86c448c291a',
    messagingSenderId: '312635116271',
    projectId: 'wallpeezer',
    authDomain: 'wallpeezer.firebaseapp.com',
    storageBucket: 'wallpeezer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFyDJzMO0danJ_e-ZODV_uAHpnOOKzsns',
    appId: '1:312635116271:android:08eff4340fa567d18c291a',
    messagingSenderId: '312635116271',
    projectId: 'wallpeezer',
    storageBucket: 'wallpeezer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIUSJ3_LZO4hS8o1hckfoLhD9iJdzl--8',
    appId: '1:312635116271:ios:f5ba66538aba964e8c291a',
    messagingSenderId: '312635116271',
    projectId: 'wallpeezer',
    storageBucket: 'wallpeezer.firebasestorage.app',
    iosBundleId: 'com.example.wallpeezer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIUSJ3_LZO4hS8o1hckfoLhD9iJdzl--8',
    appId: '1:312635116271:ios:f5ba66538aba964e8c291a',
    messagingSenderId: '312635116271',
    projectId: 'wallpeezer',
    storageBucket: 'wallpeezer.firebasestorage.app',
    iosBundleId: 'com.example.wallpeezer',
  );

}